
package formulario;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class clientes extends javax.swing.JFrame {

//llanar la conexion
      Connection co = conexion.conectar();
     
    
    public clientes() {
        initComponents();
        setLocationRelativeTo(null);
        limpiartabla();
        Listar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidentificacioncliente = new javax.swing.JTextField();
        txtnombrecliente = new javax.swing.JTextField();
        txtdireccionclientes = new javax.swing.JTextField();
        txttelefonocliente = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaclientes = new javax.swing.JTable();
        btnactualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtidcliente = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes ");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        jLabel1.setText("NIT / IDENTIFICACION:");

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        jLabel2.setText("NOMBRE:");

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        jLabel3.setText("DIRECCION / CORREO:");

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        jLabel4.setText("TELEFONO:");

        txtidentificacioncliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidentificacionclienteKeyReleased(evt);
            }
        });

        btnagregar.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clientenuevo32.png"))); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnagregar.setIconTextGap(0);
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "IDENTIFICACION", "NOMBRE", "DIRECCION", "TELEFONO"
            }
        ));
        tablaclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaclientes);
        if (tablaclientes.getColumnModel().getColumnCount() > 0) {
            tablaclientes.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        btnactualizar.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar32.png"))); // NOI18N
        btnactualizar.setText("ACTUALIZAR");
        btnactualizar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnactualizar.setIconTextGap(0);
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        jLabel5.setText("ID:");

        txtidcliente.setEnabled(false);

        btneliminar.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar32.png"))); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnlimpiar.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limpiar32.png"))); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnlimpiar.setIconTextGap(0);
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnagregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar)
                        .addGap(14, 14, 14)
                        .addComponent(btnlimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidentificacioncliente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdireccionclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttelefonocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(142, 142, 142)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidentificacioncliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdireccionclientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefonocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar)
                    .addComponent(btnactualizar)
                    .addComponent(btneliminar)
                    .addComponent(btnlimpiar))
                .addGap(128, 128, 128))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        agregarcliente();
          limpiartabla();
          limpiar();
          Listar();
        
        
    }//GEN-LAST:event_btnagregarActionPerformed


//evento para colocar los datos seleccionados en la tabla en las cajas de texto
    private void tablaclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaclientesMouseClicked
        int filaseleccionada = tablaclientes.rowAtPoint(evt.getPoint());
        
        txtidcliente.setText(tablaclientes.getValueAt(filaseleccionada,0).toString());
        txtidentificacioncliente.setText(tablaclientes.getValueAt(filaseleccionada,1).toString());
        txtnombrecliente.setText(tablaclientes.getValueAt(filaseleccionada,2).toString());
        txtdireccionclientes.setText(tablaclientes.getValueAt(filaseleccionada,3).toString());
        txttelefonocliente.setText(tablaclientes.getValueAt(filaseleccionada,4).toString());
    }//GEN-LAST:event_tablaclientesMouseClicked

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
          actualizarcliente();
          limpiartabla();
          limpiar();
          Listar();
               
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        eliminarcliente();
        limpiartabla();
        limpiar();
        Listar();
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
       limpiartabla();
       limpiar();
       Listar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txtidentificacionclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidentificacionclienteKeyReleased
        limpiartabla();
        buscar(txtidentificacioncliente.getText());
    }//GEN-LAST:event_txtidentificacionclienteKeyReleased

    
    //agregar nuevo cliente a la base de datos
    public void agregarcliente(){
    
    String sql ="insert into clientes(identificacion,nombre,direccion,telefono)values(?,?,?,?)";
    
   
        try {
            PreparedStatement pst=co.prepareStatement(sql);
            
            pst.setString(1,txtidentificacioncliente.getText());
            pst.setString(2,txtnombrecliente.getText());
            pst.setString(3,txtdireccionclientes.getText());
            pst.setString(4,txttelefonocliente.getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"cliente guardado");
          
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error, cliente no guardado"+ e.getMessage());
        }
    }
    
    //limpiar las cajas de texto 
public void limpiar(){
    txtidentificacioncliente.setText("");
    txtnombrecliente.setText("");
    txtdireccionclientes.setText("");
    txttelefonocliente.setText("");
    txtidcliente.setText("");
}


//actualizar registro en la base de datos
public void actualizarcliente(){ 
    try{
        
    
    PreparedStatement pps=co.prepareStatement("update clientes set identificacion='"+txtidentificacioncliente.getText()+"',nombre='"+txtnombrecliente.getText()+"',direccion='"+txtdireccionclientes.getText()+"',telefono='"+txttelefonocliente.getText()+"' where id ='"+txtidcliente.getText()+"'");
    
    pps.executeUpdate();
    JOptionPane.showMessageDialog(null,"datos actualizados");
    
    }     catch (HeadlessException | SQLException e) {
              
               JOptionPane.showMessageDialog(null,"Error, Datos no guardados  "+ e.getMessage());
          }      
              
}


//eliminar registro en la base de datos
public void eliminarcliente(){
    int fila =tablaclientes.getSelectedRow();
    
    try{
        String sql ="delete from clientes where id="+tablaclientes.getValueAt(fila, 0);
        Statement st=co.createStatement();
        int n =st.executeUpdate(sql);
        if(n>= 0){
            JOptionPane.showMessageDialog(null,"Cliente Eliminado");
           
           
        }
    }     catch (HeadlessException | SQLException e) {
             JOptionPane.showMessageDialog(null,"Error, no se puedo eliminar cliente "+e.getMessage());
          }
}

    
    
    
  //buscar o mostrar todo slos registro de la base de datos en la tabla  

 public void Listar(){
     Statement st;
      ResultSet rs;
     DefaultTableModel modelo;
        String sql="select *from clientes";
        try{
            
            st=co.createStatement();
            rs=st.executeQuery(sql);
            Object[]clientes=new Object[5];
            modelo=(DefaultTableModel)tablaclientes.getModel();
            while(rs.next()){
                clientes[0]=rs.getInt("id");
                clientes[1]=rs.getString("identificacion");
                clientes[2]=rs.getString("nombre");
                clientes[3]=rs.getString("direccion");
                clientes[4]=rs.getString("telefono");
                modelo.addRow(clientes);
            }
            tablaclientes.setModel(modelo);
        } catch (SQLException e) {
      JOptionPane.showMessageDialog(null,"Error "+ e.getMessage());
    }
    }
 
 
 //limpiar tabla
  public void limpiartabla(){
      
      DefaultTableModel model =(DefaultTableModel)tablaclientes.getModel();
      model.setRowCount(0);
    
        }
  
  
  //buscar registro cuando se escribe em la caja de texto identificacion
 public void buscar(String valor){
     Statement st;
      ResultSet rs;
     DefaultTableModel modelo;
        String sql="select *  from clientes where identificacion like '%"+valor+"%'";
        try{
            
            st=co.createStatement();
            rs=st.executeQuery(sql);
            Object[]clientes=new Object[5];
            modelo=(DefaultTableModel)tablaclientes.getModel();
            while(rs.next()){
                clientes[0]=rs.getInt("id");
                clientes[1]=rs.getString("identificacion");
                clientes[2]=rs.getString("nombre");
                clientes[3]=rs.getString("direccion");
                clientes[4]=rs.getString("telefono");
                modelo.addRow(clientes);
            }
            tablaclientes.setModel(modelo);
        } catch (SQLException e) {
       JOptionPane.showMessageDialog(null,"Error " +e.getMessage());
    }
    
 }
  
  
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new clientes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaclientes;
    private javax.swing.JTextField txtdireccionclientes;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JTextField txtidentificacioncliente;
    private javax.swing.JTextField txtnombrecliente;
    private javax.swing.JTextField txttelefonocliente;
    // End of variables declaration//GEN-END:variables
}
